SET PATH=C:\HARBOUR\BIN;C:\MINGW-4.8.1\BIN;%PATH%
SET INCLUDE=c:\mingw-4.8.1\lib\gcc\mingw32\4.8.1\include
SET CPATH=C:\MINGW-4.8.1
SET C_INCLUDE_PATH=C:\MINGW-4.8.1\INCLUDE;C:\HARBOUR\INCLUDE
SET CPLUS_INCLUDE_PATH=C:\MINGW-4.8.1\INCLUDE;C:\HARBOUR\INCLUDE
SET COBJC_INCLUDE_PATH=C:\MINGW-4.8.1\INCLUDE;C:\HARBOUR\INCLUDE
SET C_LIB_PATH=C:\MINGW-4.8.1\LIB;C:\HARBOUR\LIB
